const contacts = [
  {
    id: 1,
    name: "Ronald Robertson",
    role: "Creative Director",
    email: "ronald@example.com",
    phone: "+1 (070) 123-8459",
    location: "New York, NY",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    online: true,
  },
  {
    id: 2,
    name: "Regina Cooper",
    role: "Project Manager",
    email: "regina@example.com",
    phone: "+1 (070) 222-4589",
    location: "California",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    online: true,
  },
  {
    id: 3,
    name: "Judith Black",
    role: "UI Designer",
    email: "judith@example.com",
    phone: "+1 (070) 333-4589",
    location: "Texas",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    online: false,
  },
  {
    id: 4,
    name: "Dustin Williamson",
    role: "Web Developer",
    email: "dustin@example.com",
    phone: "+1 (070) 444-4589",
    location: "Chicago",
    avatar: "https://randomuser.me/api/portraits/men/75.jpg",
    online: true,
  },
  {
    id: 5,
    name: "Nathan Fox",
    role: "Business Analyst",
    email: "nathan@example.com",
    phone: "+1 (070) 555-4589",
    location: "Seattle",
    avatar: "https://randomuser.me/api/portraits/men/51.jpg",
    online: false,
  },
  {
    id: 6,
    name: "Calvin Flores",
    role: "Graphic Designer",
    email: "calvin@example.com",
    phone: "+1 (070) 666-4589",
    location: "Boston",
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    online: true,
  },
  {
    id: 7,
    name: "Courtney Nguyen",
    role: "Product Designer",
    email: "courtney@example.com",
    phone: "+1 (070) 777-4589",
    location: "Florida",
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    online: true,
  },
  {
    id: 8,
    name: "Brandon Pena",
    role: "Software Engineer",
    email: "brandon@example.com",
    phone: "+1 (070) 888-4589",
    location: "San Francisco",
    avatar: "https://randomuser.me/api/portraits/men/41.jpg",
    online: false,
  },
];

export default contacts;